"use client";

import { useCallback, useEffect, useState } from "react";

type EvidenceItem = { documentId: string; objectiveId: string; objectiveTitle: string; filename: string; category: string; bookTitle: string; uploadedEdition: string; sourceKind: string; edition: string; publicationDate: string; reviewedAt: string; reviewDueAt: string; decision: string; conflictNote: string; reviewerNote: string; updatedAt: string; due: boolean; state: string };
type Summary = { total: number; needsReview: number; current: number; due: number; superseded: number; conflicts: number };

export function EvidenceGovernanceWorkspace() {
  const [items, setItems] = useState<EvidenceItem[]>([]);
  const [summary, setSummary] = useState<Summary>({ total: 0, needsReview: 0, current: 0, due: 0, superseded: 0, conflicts: 0 });
  const [drafts, setDrafts] = useState<Record<string, EvidenceItem>>({});
  const [message, setMessage] = useState("");
  const key = (item: EvidenceItem) => `${item.documentId}:${item.objectiveId}`;
  const load = useCallback(async () => { const response = await fetch("/api/evidence-governance"); if (!response.ok) return; const data = await response.json(); setItems(data.items ?? []); if (data.summary) setSummary(data.summary); setDrafts(Object.fromEntries((data.items ?? []).map((item: EvidenceItem) => [`${item.documentId}:${item.objectiveId}`, item]))); }, []);
  useEffect(() => { let active = true; fetch("/api/evidence-governance").then((response) => response.ok ? response.json() : null).then((data) => { if (!active || !data) return; setItems(data.items ?? []); if (data.summary) setSummary(data.summary); setDrafts(Object.fromEntries((data.items ?? []).map((item: EvidenceItem) => [`${item.documentId}:${item.objectiveId}`, item]))); }).catch(() => undefined); return () => { active = false; }; }, []);
  function update(item: EvidenceItem, field: keyof EvidenceItem, value: string) { setDrafts((current) => ({ ...current, [key(item)]: { ...(current[key(item)] ?? item), [field]: value } })); }
  async function save(item: EvidenceItem) {
    const draft = drafts[key(item)] ?? item; setMessage("Saving the review and adding it to the change log…");
    try { const response = await fetch("/api/evidence-governance", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(draft) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Evidence review could not be saved."); setMessage("Freshness review saved. No clinical claim was changed automatically."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Evidence review could not be saved."); }
  }
  return <div className="evidence-page"><header className="evidence-hero"><div><span className="eyebrow"><i /> Recommendation 48 · Evidence freshness</span><h1>Know when the source<br />needs another look.</h1><p>Record edition, publication date, review date, next check, conflicts, and superseded material. A flag can stop teaching—but it can never silently rewrite a clinical claim.</p><a className="primary-button primary-button--dark" href="/library">Open private library <span>→</span></a></div><div>{[[summary.current, "current"], [summary.needsReview, "unreviewed"], [summary.due, "due"], [summary.conflicts, "conflicts"]].map(([value, label]) => <span key={label}><strong>{value}</strong><small>{label}</small></span>)}</div></header>
    <aside className="evidence-rule"><span>⌁</span><div><strong>Freshness is a governance signal, not an automatic medical update.</strong><p>Inspect the source, document the decision, then separately review any lesson or question affected by a change.</p></div><a href="/history">Open change history</a></aside>
    <section className="evidence-register"><header className="section-header"><div><span className="eyebrow">Owner-only register</span><h2>Source review cards</h2></div><span>{summary.total} evidence scopes</span></header><div>{items.map((item) => { const draft = drafts[key(item)] ?? item; return <article key={key(item)}><header><div><span>{item.category}</span><h3>{item.bookTitle || item.filename}</h3><p>{item.objectiveTitle}</p></div><b className={`evidence-state evidence-state--${item.state}`}>{item.state.replaceAll("_", " ")}</b></header><div className="evidence-fields"><label><span>Source kind</span><select value={draft.sourceKind} onChange={(event) => update(item, "sourceKind", event.target.value)}><option value="textbook">Textbook</option><option value="guideline">Guideline</option><option value="lecture">Lecture</option><option value="other">Other</option></select></label><label><span>Edition / version</span><input value={draft.edition} onChange={(event) => update(item, "edition", event.target.value)} placeholder={item.uploadedEdition || "e.g. 22nd edition"} /></label><label><span>Publication date</span><input type="date" value={draft.publicationDate} onChange={(event) => update(item, "publicationDate", event.target.value)} /></label><label><span>Reviewed on</span><input type="date" value={draft.reviewedAt} onChange={(event) => update(item, "reviewedAt", event.target.value)} /></label><label><span>Review again by</span><input type="date" value={draft.reviewDueAt} onChange={(event) => update(item, "reviewDueAt", event.target.value)} /></label><label><span>Decision</span><select value={draft.decision} onChange={(event) => update(item, "decision", event.target.value)}><option value="needs_review">Needs review</option><option value="verified_current">Verified current</option><option value="superseded">Superseded</option></select></label></div><label className="evidence-note"><span>Conflict or changed recommendation</span><textarea value={draft.conflictNote} onChange={(event) => update(item, "conflictNote", event.target.value)} placeholder="Record the disagreement; do not resolve it automatically." maxLength={3000} /></label><label className="evidence-note"><span>Reviewer note</span><textarea value={draft.reviewerNote} onChange={(event) => update(item, "reviewerNote", event.target.value)} placeholder="What did you inspect, and what still needs review?" maxLength={3000} /></label><footer><small>{item.updatedAt ? `Last saved ${new Date(item.updatedAt).toLocaleDateString()}` : "No freshness review yet"}</small><button type="button" onClick={() => save(item)}>Save reviewed status</button></footer></article>; })}</div>{!items.length ? <div className="evidence-empty"><span>◇</span><div><strong>No uploaded sources yet.</strong><p>Add a Book section or guideline to start the freshness register.</p></div><a href="/library">Upload a source →</a></div> : null}</section>{message ? <p className="evidence-message" role="status">{message}</p> : null}</div>;
}
