import { VitaeFrame } from "@/components/vitae-frame";

export const metadata = { title: "Study Tools · Poh-tah-toh", description: "Source-grounded reasoning, misconception repair, cross-book comparison, and adaptive medical learning tools." };

const tools = [
  { number: "23", title: "Smart source search", detail: "Search only uploaded book sections still attached to approved mappings, then open the chapter or saved page range.", href: "/source-search", action: "Search approved sources" },
  { number: "24", title: "Learning history", detail: "Review saved versions of notes, mind maps, mapping decisions, and lesson drafts with recoverable rollback.", href: "/history", action: "Open version history" },
  { number: "25", title: "Private backup", detail: "Download every structured learning record and source-file reference as one owner-scoped JSON archive.", href: "/backup", action: "Prepare backup" },
  { number: "26", title: "Deep PDF & Word search", detail: "Extract text and use on-device OCR for small scanned sections, then search approved passages by page.", href: "/source-search", action: "Search inside sources" },
  { number: "27", title: "Source-linked reader", detail: "Read indexed pages, highlight exact passages, and attach the page citation directly to lesson notes.", href: "/library", action: "Open source library" },
  { number: "28", title: "Citation-first Professor", detail: "Place approved extracted evidence before teaching and keep every explanation or later connection visibly labeled.", href: "/learn/cardiovascular/cardiac-cycle", action: "Open Professor Mode" },
  { number: "29", title: "Objective-level coverage", detail: "Trace every syllabus objective through chapter, exact page, uploaded section, lesson, recall, questions, and visible remaining gaps.", href: "/coverage", action: "Inspect objective paths" },
  { number: "30", title: "Adaptive daily queue", detail: "Choose today’s lesson, recall, mistakes, practice, and revision from weakness, due dates, and saved learning evidence.", href: "/today", action: "Open today’s queue" },
  { number: "31", title: "Smarter spaced repetition", detail: "Adjust review intervals using accuracy, difficulty, confidence, response speed, overdue time, and personal lapse history.", href: "/review", action: "Open adaptive review" },
  { number: "32", title: "Approved-source questions", detail: "Create MCQ, SAQ, viva, and clinical-case drafts from an exact approved passage, then hold each behind human review.", href: "/question-studio", action: "Open question studio" },
  { number: "33", title: "Clinical reasoning ladder", detail: "Move from normal physiology to mechanism, symptoms, examination, investigation, and management without skipping unsupported links.", href: "/reasoning-ladder", action: "Build a reasoning chain" },
  { number: "34", title: "Misconception detector", detail: "Group repeated incorrect answers and recall lapses into concept patterns, then complete a short corrective lesson.", href: "/misconceptions", action: "Inspect error patterns" },
  { number: "35", title: "Cross-book comparison", detail: "Compare exact passages from two approved books, inspect differences in emphasis, and review cautious disagreement flags.", href: "/source-compare", action: "Compare approved books" },
  { number: "36", title: "Connected note workspace", detail: "Link every note and sideways-map node to its syllabus objective, exact saved passage, approved question, and personal mistake.", href: "/note-workspace", action: "Connect learning evidence" },
  { number: "37", title: "Visual version comparison", detail: "Choose two saved versions and inspect every changed note line, map node, mapping field, or lesson field before restoration.", href: "/history", action: "Compare versions" },
  { number: "38", title: "Backup restoration", detail: "Preview a private backup, detect duplicates, select record groups, and restore without overwriting current learning data.", href: "/backup", action: "Preview a backup" },
  { number: "39", title: "Custom offline packs", detail: "Choose a clinical subject, body system, or examination block to carry offline instead of downloading one fixed pack.", href: "/offline", action: "Build an offline pack" },
  { number: "40", title: "High-speed processing", detail: "Use durable batch jobs, an incremental term index, and short-lived search caching so growing source libraries remain responsive.", href: "/library#processing", action: "Open processing dock" },
  { number: "41", title: "Gold-standard cardiovascular pathway", detail: "Follow normal foundations, clinical competencies, prerequisites, source gates, and measurable proof in one route.", href: "/cardiovascular-pathway", action: "Open complete pathway" },
  { number: "42", title: "Adaptive Professor Mode 2.0", detail: "Target the weakest saved mechanism with layered hints, teach-back scoring, and visible source labels.", href: "/cardiovascular-pathway#professor-2", action: "Start adaptive teaching" },
  { number: "43", title: "Prerequisite competency graph", detail: "See what must be understood before each cardiovascular clinical objective can safely unlock.", href: "/cardiovascular-pathway#pathway-map", action: "Inspect prerequisites" },
  { number: "44", title: "Cumulative progress testing", detail: "Retest repair, retention, and transfer questions on a risk-adjusted interval instead of declaring mastery once.", href: "/cardiovascular-pathway#progress-test", action: "Take progress test" },
  { number: "45", title: "Clinical encounter simulator", detail: "Move from history to communication through a branching encounter with scored source stops at unsupported decisions.", href: "/clinical-encounter", action: "Start encounter" },
  { number: "46", title: "Question-quality laboratory", detail: "Inspect personal difficulty, distractor use, and cautious separation signals, then individually keep, review, or retire an item.", href: "/question-quality", action: "Inspect question quality" },
  { number: "47", title: "Strict mastery proof", detail: "Require recall, explanation, application, and delayed retention—with no open mistake—before a topic becomes mastered.", href: "/mastery-proof", action: "Open mastery gates" },
  { number: "48", title: "Evidence freshness", detail: "Track source edition, review dates, conflicts, and superseded evidence without silently changing clinical teaching.", href: "/evidence-governance", action: "Review evidence dates" },
];

export default function StudyToolsPage() {
  return <VitaeFrame active="archive" title="Study tools" subtitle="Learn · Features 23–48"><div className="study-tools-page"><header className="study-tools-hero"><div><span className="eyebrow"><i /> Trace · compare · prove · refresh</span><h1>Your sources now drive<br />the whole learning day.</h1><p>Trace every objective to evidence, reason through clinical encounters, prove durable mastery, review question quality, and keep the evidence itself current.</p><a className="primary-button primary-button--dark" href="/clinical-encounter">Open clinical encounter <span>→</span></a></div><div><strong>26</strong><span>connected learning safeguards</span><p>Each operation remains source-gated, reviewable, owner-scoped, and built for a larger future library.</p></div></header><section className="study-tool-grid">{tools.map((tool) => <a href={tool.href} key={tool.number}><span>{tool.number}</span><small>Recommendation {tool.number}</small><strong>{tool.title}</strong><p>{tool.detail}</p><b>{tool.action} →</b></a>)}</section><aside className="study-tools-rule"><span>⌁</span><div><strong>Source files remain private and separate.</strong><p>Text and OCR extraction happens on your device, indexed passages remain owner-scoped, and original textbook bytes are never exposed in structured exports.</p></div><a href="/evidence-governance">Review evidence freshness</a></aside></div></VitaeFrame>;
}
