"use client";

import { useEffect, useState } from "react";
import { learningGraph } from "@/lib/learning-engine";

type GraphNode = (typeof learningGraph)[number] & { state?: string };
type Evidence = { diagnostics: number; cases: number; visuals: number; interleaved: number; professorDialogues: number; cumulativeTests: number; vivas: number; highConfidenceWrong: number; openMistakes: number; dueReviews: number; sourceDocuments: number; approvedMappings: number };

export function LearningGraphWorkspace() {
  const [nodes, setNodes] = useState<GraphNode[]>(learningGraph);
  const [evidence, setEvidence] = useState<Evidence>({ diagnostics: 0, cases: 0, visuals: 0, interleaved: 0, professorDialogues: 0, cumulativeTests: 0, vivas: 0, highConfidenceWrong: 0, openMistakes: 0, dueReviews: 0, sourceDocuments: 0, approvedMappings: 0 });
  useEffect(() => { let active = true; fetch("/api/learning-engine").then((response) => response.ok ? response.json() : null).then((data) => { if (!active || !data) return; if (data.graph) setNodes(data.graph); if (data.evidence) setEvidence(data.evidence); }).catch(() => undefined); return () => { active = false; }; }, []);
  return <div className="learning-graph-page"><header className="learning-graph-hero"><div><span className="eyebrow"><i /> Recommendation 14 · Unified graph</span><h1>Every activity has<br />a reason and a destination.</h1><p>The graph connects what the syllabus requires to the source that supports it, the lesson that teaches it, and the evidence that proves mastery.</p></div><a className="primary-button primary-button--dark" href="/diagnostic">Update with a diagnostic <span>→</span></a></header>
    <section className="graph-evidence"><span><strong>{evidence.sourceDocuments}</strong><small>source documents</small></span><span><strong>{evidence.approvedMappings}</strong><small>approved mappings</small></span><span><strong>{evidence.diagnostics}</strong><small>diagnostics</small></span><span><strong>{evidence.professorDialogues}</strong><small>teach-backs</small></span><span><strong>{evidence.cases}</strong><small>cases</small></span><span><strong>{evidence.visuals}</strong><small>visual labs</small></span><span><strong>{evidence.interleaved}</strong><small>mixed reviews</small></span><span><strong>{evidence.cumulativeTests}</strong><small>progress tests</small></span><span><strong>{evidence.vivas}</strong><small>oral vivas</small></span><span><strong>{evidence.highConfidenceWrong}</strong><small>confidence risks</small></span></section>
    <section className="unified-graph" aria-labelledby="unified-graph-title"><header className="section-header"><div><span className="eyebrow">Live learning chain</span><h2 id="unified-graph-title">Objective to mastery</h2></div><span>Choose any node to open it</span></header><div>{nodes.map((node, index) => <a className={`graph-node graph-node--${node.state ?? "mapped"}`} href={node.href} key={node.id}><span>{String(index + 1).padStart(2, "0")}</span><small>{node.lane}</small><strong>{node.title}</strong><p>{node.detail}</p><b>{node.state === "evidence" ? "Evidence saved" : node.state === "active" ? "Active now" : node.state === "ready" ? "Ready" : "Mapped"}</b>{index < nodes.length - 1 ? <i aria-hidden="true">→</i> : null}</a>)}</div></section>
    <aside className="graph-principle"><span>⌁</span><div><strong>Source gates remain in control.</strong><p>The graph can recommend only live lessons and source-trailed activities. Mapped disease topics stay locked until their sections are approved.</p></div><a href="/coverage">Inspect coverage</a></aside>
  </div>;
}
