"use client";

import { useEffect, useMemo, useState } from "react";

type BlueprintObjective = { id: string; subject: string; system: string; week: string; topic: string; modalities: string[]; importance: string; estimateBasis: string; readiness: string; liveEvidence: number };
type BlueprintData = { objectives: BlueprintObjective[]; summary: { total: number; high: number; withEvidence: number; sourceMissing: number; modalityCounts: Record<string, number> } };
const empty: BlueprintData = { objectives: [], summary: { total: 68, high: 0, withEvidence: 0, sourceMissing: 0, modalityCounts: {} } };

export function ExamBlueprintWorkspace() {
  const [data, setData] = useState<BlueprintData>(empty);
  const [subject, setSubject] = useState("All");
  const [modality, setModality] = useState("All");
  const [priority, setPriority] = useState("All");
  const [query, setQuery] = useState("");
  useEffect(() => { let active = true; fetch("/api/exam-blueprint").then((response) => response.ok ? response.json() : null).then((payload) => { if (active && payload) setData(payload); }).catch(() => undefined); return () => { active = false; }; }, []);
  const visible = useMemo(() => data.objectives.filter((item) => (subject === "All" || item.subject === subject) && (modality === "All" || item.modalities.includes(modality)) && (priority === "All" || item.importance === priority) && `${item.topic} ${item.system}`.toLowerCase().includes(query.toLowerCase())), [data.objectives, subject, modality, priority, query]);
  return <div className="blueprint-page"><header className="blueprint-hero"><div><span className="eyebrow"><i /> Recommendation 22 · Exam blueprint</span><h1>Every objective needs<br />an assessment lane.</h1><p>Connect the 68 Semester 7 objectives to MCQ, SAQ, OSCE, and viva practice. Importance is a transparent planning estimate—not an official university weighting.</p></div><div><strong>{data.summary.total}</strong><span>syllabus objectives</span><p>{data.summary.withEvidence} currently have connected learning evidence</p></div></header><section className="blueprint-metrics">{["MCQ", "SAQ", "OSCE", "Viva"].map((item) => <article key={item}><span>{item}</span><strong>{data.summary.modalityCounts[item] ?? 0}</strong><small>planned objectives</small></article>)}</section><section className="blueprint-workspace"><header><label><span>Search objectives</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search topic or system" /></label><label><span>Subject</span><select value={subject} onChange={(event) => setSubject(event.target.value)}><option>All</option><option>Internal Medicine I</option><option>Perioperative Medicine I</option><option>Women &amp; Child Health I</option></select></label><label><span>Format</span><select value={modality} onChange={(event) => setModality(event.target.value)}><option>All</option><option>MCQ</option><option>SAQ</option><option>OSCE</option><option>Viva</option></select></label><label><span>Priority</span><select value={priority} onChange={(event) => setPriority(event.target.value)}><option>All</option><option>High</option><option>Medium</option><option>Foundation</option></select></label></header><div className="blueprint-table"><div className="blueprint-table-head"><span>Objective</span><span>Assessment lanes</span><span>Working priority</span><span>Readiness</span></div>{visible.map((item) => <article key={item.id}><div><small>{item.subject} · {item.system} · Week {item.week}</small><strong>{item.topic}</strong></div><div className="blueprint-formats">{item.modalities.map((format) => <span key={format}>{format}</span>)}</div><b className={`blueprint-priority blueprint-priority--${item.importance.toLowerCase()}`}>{item.importance}</b><span className={`blueprint-readiness blueprint-readiness--${item.readiness}`}>{item.liveEvidence ? `${item.liveEvidence} evidence items` : item.readiness.replaceAll("_", " ")}</span></article>)}</div><footer><span>Showing {visible.length} of {data.summary.total} objectives</span><p>Format and priority assignments are planning estimates derived from syllabus wording and listed assessment methods. Confirm them with the official exam brief.</p></footer></section></div>;
}
