"use client";

import { useEffect, useState } from "react";

type Summary = { lessons: number; notes: number; sourceFiles: number; sourceCitations: number; sourceMappings: number; lessonDrafts: number; recallCards: number; adaptiveReviewSignals: number; dailyQueueActions: number; generatedQuestions: number; approvedSupportSources: number; clinicalReasoningStages: number; misconceptionRepairs: number; assessmentAttempts: number; learningActivities: number; mistakes: number; mindMaps: number; savedVersions: number; masteryScore: number };
const empty: Summary = { lessons: 0, notes: 0, sourceFiles: 0, sourceCitations: 0, sourceMappings: 0, lessonDrafts: 0, recallCards: 0, adaptiveReviewSignals: 0, dailyQueueActions: 0, generatedQuestions: 0, approvedSupportSources: 0, clinicalReasoningStages: 0, misconceptionRepairs: 0, assessmentAttempts: 0, learningActivities: 0, mistakes: 0, mindMaps: 0, savedVersions: 0, masteryScore: 0 };

export function BackupWorkspace() {
  const [summary, setSummary] = useState<Summary>(empty);
  const [scope, setScope] = useState("Preparing your private archive summary…");
  useEffect(() => { let active = true; fetch("/api/backup?mode=summary").then((response) => response.ok ? response.json() : null).then((payload) => { if (active && payload) { setSummary(payload.summary); setScope(payload.scope); } }).catch(() => setScope("The archive summary could not be loaded, but you can still retry the download.")); return () => { active = false; }; }, []);
  const recordCount = summary.lessons + summary.notes + summary.sourceMappings + summary.sourceCitations + summary.lessonDrafts + summary.recallCards + summary.adaptiveReviewSignals + summary.dailyQueueActions + summary.generatedQuestions + summary.approvedSupportSources + summary.clinicalReasoningStages + summary.misconceptionRepairs + summary.assessmentAttempts + summary.learningActivities + summary.mistakes + summary.mindMaps + summary.savedVersions;
  return <div className="backup-page"><header className="backup-hero"><div><span className="eyebrow"><i /> Recommendation 25 · Private backup</span><h1>One private archive.<br />Every learning record.</h1><p>Download notes, progress, mistakes, mastery, reasoning stages, misconception repairs, support-source approvals, assessments, citations, and history as structured JSON.</p><a className="primary-button primary-button--dark" href="/api/backup" download>Download private backup <span>↓</span></a></div><div><strong>{recordCount}</strong><span>structured records ready</span><p>Current mastery snapshot: {summary.masteryScore}%</p></div></header><section className="backup-metrics"><article><span>Learning</span><strong>{summary.lessons + summary.notes + summary.recallCards + summary.adaptiveReviewSignals + summary.dailyQueueActions + summary.clinicalReasoningStages}</strong><p>progress, notes, recall signals, daily choices, and reasoning links</p></article><article><span>Assessment</span><strong>{summary.assessmentAttempts + summary.learningActivities + summary.mistakes + summary.generatedQuestions + summary.misconceptionRepairs}</strong><p>attempts, corrections, repairs, and reviewed question drafts</p></article><article><span>Sources</span><strong>{summary.sourceMappings + summary.sourceCitations + summary.lessonDrafts + summary.approvedSupportSources}</strong><p>mapping decisions, citations, drafts, and support-book reviews</p></article><article><span>Creative work</span><strong>{summary.mindMaps + summary.savedVersions}</strong><p>mind maps and recoverable versions</p></article></section><section className="backup-contents"><header className="section-header"><div><span className="eyebrow">Archive contents</span><h2>What the download protects</h2></div><span>JSON · private · owner-scoped</span></header><div><article><span>Included</span><strong>All structured learning data</strong><p>Records are grouped by type and include a generated-at date, schema version, summary, and current mastery snapshot.</p></article><article><span>Privacy</span><strong>Internal identity removed</strong><p>The stable owner identifier and private storage object keys are excluded from the downloaded file.</p></article><article><span>Source files</span><strong>Inventory, not duplicated bytes</strong><p>Book titles, sections, page ranges, filenames, index status, and saved short citations are included. Full extracted book text and original file bytes remain in your private library.</p></article></div></section><aside className="backup-rule"><span>⌁</span><div><strong>Store the downloaded file somewhere private.</strong><p>{scope} It may contain your notes, answers, citations, and correction history.</p></div><a href="/history">Review version history</a></aside></div>;
}
