"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Item = { id: string; sourceKind: string; prompt: string; options: string[]; correctOption: number; sourceLabel: string; attempts: number; correctRate: number | null; discrimination: number | null; optionCounts: Array<{ option: string; count: number; correct: boolean }>; automaticFlags: string[]; decision: string; reviewerNote: string; updatedAt: string };
type Summary = { total: number; delivered: number; reviewNeeded: number; retired: number };

export function QuestionQualityWorkspace() {
  const [items, setItems] = useState<Item[]>([]);
  const [summary, setSummary] = useState<Summary>({ total: 0, delivered: 0, reviewNeeded: 0, retired: 0 });
  const [methodology, setMethodology] = useState("");
  const [filter, setFilter] = useState("all");
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/question-quality"); if (!response.ok) return; const data = await response.json(); setItems(data.items ?? []); if (data.summary) setSummary(data.summary); setMethodology(data.methodology ?? ""); setNotes(Object.fromEntries((data.items ?? []).map((item: Item) => [item.id, item.reviewerNote]))); }, []);
  useEffect(() => { let active = true; fetch("/api/question-quality").then((response) => response.ok ? response.json() : null).then((data) => { if (!active || !data) return; setItems(data.items ?? []); if (data.summary) setSummary(data.summary); setMethodology(data.methodology ?? ""); setNotes(Object.fromEntries((data.items ?? []).map((item: Item) => [item.id, item.reviewerNote]))); }).catch(() => undefined); return () => { active = false; }; }, []);
  const visible = useMemo(() => items.filter((item) => filter === "all" || filter === "flagged" && item.automaticFlags.length || item.decision === filter), [filter, items]);
  async function decide(item: Item, decision: "active" | "review_needed" | "retired") {
    setMessage("Saving the individual review decision…");
    try { const response = await fetch("/api/question-quality", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ questionKey: item.id, decision, reviewerNote: notes[item.id] ?? "" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Review could not be saved."); setMessage(decision === "retired" ? "Question retired in the quality register; its history remains visible and it can be re-enabled after review." : "Review decision saved."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Review could not be saved."); }
  }
  return <div className="quality-page"><header className="quality-hero"><div><span className="eyebrow"><i /> Recommendation 46 · Question-quality laboratory</span><h1>Make every question<br />earn its place.</h1><p>Inspect difficulty, distractor choices, and a cautious separation signal from your own repeated attempts. Statistics suggest review; only you can retire a question.</p><a className="primary-button primary-button--dark" href="/question-studio">Open source-backed studio <span>→</span></a></div><div>{[[summary.delivered, "delivered"], [summary.reviewNeeded, "review"], [summary.retired, "retired"]].map(([value, label]) => <span key={label}><strong>{value}</strong><small>{label}</small></span>)}</div></header>
    <aside className="quality-method"><span>i</span><div><strong>Personal signal, not cohort psychometrics.</strong><p>{methodology || "Stable flags wait for enough repeated attempts; small samples stay explicitly uncertain."}</p></div></aside>
    <section className="quality-lab"><header className="section-header"><div><span className="eyebrow">Individual human review</span><h2>Question inventory</h2></div><label><span className="sr-only">Filter questions</span><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All {summary.total}</option><option value="flagged">Automatic flags</option><option value="review_needed">Needs review</option><option value="retired">Retired</option></select></label></header><div className="quality-grid">{visible.map((item) => <article className={item.decision === "retired" ? "is-retired" : ""} key={item.id}><header><span>{item.sourceKind}</span><b>{item.decision.replaceAll("_", " ")}</b></header><h3>{item.prompt}</h3><div className="quality-signals"><span><strong>{item.attempts}</strong><small>attempts</small></span><span><strong>{item.correctRate === null ? "—" : `${item.correctRate}%`}</strong><small>correct</small></span><span><strong>{item.discrimination === null ? "—" : `${item.discrimination > 0 ? "+" : ""}${item.discrimination}`}</strong><small>separation</small></span></div><div className="quality-options">{item.optionCounts.map((option, index) => <span className={option.correct ? "is-key" : ""} key={option.option}><i>{String.fromCharCode(65 + index)}</i><b>{option.option}</b><small>{option.count} chosen</small></span>)}</div><div className="quality-flags">{item.automaticFlags.map((flag) => <span key={flag}>{flag}</span>)}{!item.automaticFlags.length ? <span className="is-clear">No automatic review flag</span> : null}</div><small className="quality-source">{item.sourceLabel}</small><label><span>Reviewer note</span><textarea value={notes[item.id] ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [item.id]: event.target.value }))} maxLength={2000} placeholder="Why should this item stay, change, or retire?" /></label><footer><button type="button" onClick={() => decide(item, "active")}>Keep active</button><button type="button" onClick={() => decide(item, "review_needed")}>Needs review</button><button type="button" onClick={() => decide(item, "retired")}>Retire</button></footer></article>)}</div>{!visible.length ? <p className="quality-empty">No questions match this filter.</p> : null}</section>{message ? <p className="quality-message" role="status">{message}</p> : null}</div>;
}
